#!/bin/sh

echo "Publish changes"
echo "compile"
cd ../ && yarn build:prod

echo "Eliminar contenido docs"
rm -rf docs/

echo "Actualizar nuevo contenido"
cp -rf dist/* docs/

echo "git push"
git add .
git commit -m "automatización de publicación"
git push